name: mediCore

services:
  #  mediCore-database:
  #    image: postgres:latest
  #    container_name: mediCore-database
  #    restart: always
  #    environment:
  #      POSTGRES_DB: mediCore_db
  #      POSTGRES_USER: postgres
  #      POSTGRES_PASSWORD: postgres
  #      PGDATA: /var/lib/postgresql/data/pgdata
  #    ports:
  #      - "5432:5432"
  #    volumes:
  #      - pgdata:/var/lib/postgresql/data

  mediCore-session:
    image: redis:latest
    container_name: mediCore_redis
    restart: always
    command: redis-server --requirepass admin
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  #  pgdata:
  redis_data: