packages:
  - '.'
allowBuilds:
  msw: true
  'unrs-resolver': true
publicHoistPattern:
  - '@inertiajs/core'
overrides:
  'eslint-plugin-react>eslint': '^9.7'
minimumReleaseAgeExclude:
  - '@rollup/rollup-linux-x64-gnu@4.61.1'
  - '@rollup/rollup-win32-x64-msvc@4.61.1'
  - '@inertiajs/core@3.3.1'
  - '@inertiajs/react@3.3.1'
  - '@inertiajs/vite@3.3.1'
  - '@inertiajs/core@3.4.0'
  - '@inertiajs/react@3.4.0'
  - '@inertiajs/vite@3.4.0'
