packages:
  - '.'
allowBuilds:
  msw: true
  'unrs-resolver': true
publicHoistPattern:
  - '@inertiajs/core'
supportedArchitectures:
  os:
    - win32
    - darwin
    - current
  cpu:
    - x64
    - arm64
minimumReleaseAgeExclude:
  - '@rollup/rollup-linux-x64-gnu@4.63.1'
  - '@rollup/rollup-win32-x64-msvc@4.63.1'
  - '@vitejs/plugin-react@6.1.1'
  - lucide-react@1.35.0 || 1.38.0
  - '@shadcn/react@0.3.1'
  - shadcn@4.19.1
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
overrides:
  vite@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
